replicaCount: 3

image:
  repository: your-registry/devops-demo
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 0.5
    memory: 512Mi
  requests:
    cpu: 0.25
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

